# Generated by Django 2.2.15 on 2020-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('genre', models.TextField(default='')),
                ('rating', models.TextField(default='')),
                ('tanggal', models.TextField(default='')),
                ('deskripsi', models.TextField(default='')),
            ],
        ),
    ]
