# Generated by Django 2.2.15 on 2020-08-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deskripsi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='genre',
            field=models.TextField(default=''),
        ),
    ]
