# Generated by Django 2.2 on 2020-09-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('genre', models.TextField(default='')),
                ('rating', models.TextField(default='')),
                ('tanggal', models.TextField(default='')),
                ('deskripsi', models.TextField(default='')),
            ],
        ),
    ]
