# Generated by Django 2.2.15 on 2020-08-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200827_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='tanggal',
            field=models.TextField(default=''),
        ),
    ]
