# Generated by Django 2.2 on 2020-09-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='judul',
        ),
    ]
