# Generated by Django 2.2 on 2020-09-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200903_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='tanggal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='genre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='tanggal',
            field=models.CharField(max_length=255),
        ),
    ]
