# Generated by Django 2.2.12 on 2021-04-25 13:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_merch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Thriler', 'Thriler'), ('Mistery', 'Mistery'), ('Fiction', 'Fiction')], default='1', max_length=25),
        ),
    ]
