# Generated by Django 2.2.12 on 2021-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='image',
            new_name='upload',
        ),
    ]
