# Generated by Django 2.2.12 on 2021-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20210425_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='upload',
            new_name='upload_img',
        ),
    ]
