# Generated by Django 2.2.12 on 2021-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20210426_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tanggal',
            field=models.DateField(max_length=255),
        ),
    ]
