# Generated by Django 2.2.12 on 2021-04-27 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20210427_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tanggal',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
