# Generated by Django 2.2.12 on 2021-04-27 19:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20210428_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Thriler', 'Thriler'), ('Mistery', 'Mistery'), ('Fiction', 'Fiction'), ('Fantasy', 'Fantasy')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
